test_job:
  image: maven:3-openjdk-17
  stage: UnitTest
  script: "mvn test"
  artifacts:
    paths:
      - "**/target/" 
    reports:
      junit: 
       - "**/target/*-reports/TEST-*.xml"
  allow_failure: true
