build_image_frontend:
    stage: build_image
    image: docker:24
    when: always
    services:
    - docker:24-dind
    before_script:
        - cd ${PROJECT_DIR_FRONT}
        - echo ${DOCKER_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin  
    script:
        # Build the Docker image
        - docker build -t ${IMAGE_NAME_FRONTEND} .
        # Push the Docker image to the registry
        - docker push ${IMAGE_NAME_FRONTEND}
