trivy:
  stage: security_scan_docker_image
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk --no-cache add curl python3 py3-pip
    - rm /usr/lib/python3.*/EXTERNALLY-MANAGED
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - docker pull ${IMAGE_NAME_BACKEND}
    - docker pull ${IMAGE_NAME_FRONTEND}
    - trivy image -f json -o TrivyScanImageBackend.json --severity HIGH,CRITICAL ${IMAGE_NAME_BACKEND}
    - trivy image -f json -o TrivyScaneImageFrontend.json --severity HIGH,CRITICAL ${IMAGE_NAME_FRONTEND}
  artifacts:
    paths:
      - TrivyScanImageBackend.json
      - TrivyScaneImageFrontend.json
    expire_in: 1 hour
